# Copyright (C) 2011-2017 Project SkyFire <https://www.projectskyfire.org/>
# Copyright (C) 2008-2017 TrinityCore <http://www.trinitycore.org/>
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

sudo: required
dist: trusty

language: cpp
compiler:
  - clang

git:
  depth: 1

before_install:
  - echo "yes" | sudo add-apt-repository ppa:george-edison55/precise-backports
  - echo "yes" | sudo add-apt-repository ppa:boost-latest/ppa
  - echo "yes" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - echo "yes" | sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main'
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get -qq update
  - sudo apt-get -qq install build-essential libtool make cmake cmake-data openssl libace-dev
  - sudo apt-get -qq install libssl-dev libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev
  - export CC=clang-3.5 CXX=clang++-3.5
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init
  
install:
  - mkdir build
  - cd build
  - cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=1 -DSCRIPTS="dynamic" -DSERVERS=1 -DNOJEM=1 -DWITH_DYNAMIC_LINKING=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_INSTALL_PREFIX=check_install
  - cd ..
 
script:
  - $CXX --version
  - cd build
  - make -j 8 -k && make install 

notifications:
  irc:
    channels:
      - "irc.rizon.net#project_skyfire"
    on_success: always
    on_failure: always
